server:
  port: 8082

spring:
  application:
    name: user

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.mycompany.com

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: ${DB_USERNAME:user_user}
    password: ${DB_PASSWORD:user_password}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:my-project-chat-ai-487408}
      credentials:
        location: ${GCP_CREDENTIALS_PATH:file:/home/shivam-sharma/.gcp/my-project-chat-ai-487408-5604b2cd4107.json}
      pubsub:
        enabled: ${GCP_PUBSUB_ENABLED:true}

# Pub/Sub subscriber for user events (signup + email verified)
user:
  pubsub:
    enabled: ${USER_PUBSUB_ENABLED:true}
    subscription: user-signup-events-sub
